<?php require VIEWS_PATH . 'includes/header.phtml'; ?>
    <div class="container">
        <!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron">
            <h1>Sobre nós!</h1>
            <div class="col-md-12">
                <h2>A Instituição</h2>
                <p>
                    orem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at pretium felis. Phasellus ac
                    arcu hendrerit, cursus diam eu, auctor sem. Phasellus nibh est, congue ut eleifend quis, sagittis eu
                    eros. Nullam euismod malesuada lorem ut consectetur. Morbi porttitor sodales dolor, consequat
                    sodales sem scelerisque eu. Etiam blandit, quam at suscipit tempor, orci dui efficitur est, vel
                    facilisis tortor velit sed ligula. Donec euismod, erat sed sodales porttitor, massa elit auctor
                    neque, maximus consequat nunc quam nec diam. Quisque velit tortor, lobortis vitae ante at, rutrum
                    efficitur magna. Donec egestas cursus volutpat. Vivamus congue magna risus, sed ultricies odio
                    aliquam quis. Suspendisse eu elit id tortor varius vulputate. In malesuada ligula augue.

                    Nulla at iaculis nunc. Nulla tempus nulla ligula. Ut id leo ut sapien maximus ultrices nec ut
                    tortor. Proin id tempus magna, nec luctus ipsum. Integer tincidunt nisl a pretium imperdiet. Etiam
                    non ullamcorper erat. Praesent in urna sit amet quam convallis accumsan a porta enim.
                </p>
                <h2>Nossas Metas</h2>
                <p>
                    orem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse at pretium felis. Phasellus ac
                    arcu hendrerit, cursus diam eu, auctor sem. Phasellus nibh est, congue ut eleifend quis, sagittis eu
                    eros. Nullam euismod malesuada lorem ut consectetur. Morbi porttitor sodales dolor, consequat
                    sodales sem scelerisque eu. Etiam blandit, quam at suscipit tempor, orci dui efficitur est, vel
                    facilisis tortor velit sed ligula. Donec euismod, erat sed sodales porttitor, massa elit auctor
                    neque, maximus consequat nunc quam nec diam. Quisque velit tortor, lobortis vitae ante at, rutrum
                    efficitur magna. Donec egestas cursus volutpat. Vivamus congue magna risus, sed ultricies odio
                    aliquam quis. Suspendisse eu elit id tortor varius vulputate. In malesuada ligula augue.
                    Nulla at iaculis nunc. Nulla tempus nulla ligula. Ut id leo ut sapien maximus ultrices nec ut
                    tortor. Proin id tempus magna, nec luctus ipsum. Integer tincidunt nisl a pretium imperdiet. Etiam
                    non ullamcorper erat. Praesent in urna sit amet quam convallis accumsan a porta enim.
                </p>
                <h2>Valores</h2>
                <p>
                    Nulla at iaculis nunc. Nulla tempus nulla ligula. Ut id leo ut sapien maximus ultrices nec ut
                    tortor. Proin id tempus magna, nec luctus ipsum. Integer tincidunt nisl a pretium imperdiet. Etiam
                    non ullamcorper erat. Praesent in urna sit amet quam convallis accumsan a porta enim.
                </p>
            </div>
        </div>

    </div> <!-- /container -->
<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>