<?php require VIEWS_PATH . 'includes/header.phtml'; ?>
    <div class="container">
        <!-- Main component for a primary marketing message or call to action -->
        <div class="jumbotron">
            <div class="col-md-12">
                <h2>Entre em contato conosco</h2>
                  <p>alexandre.programador84@gmail.com</p>
            </div>
        </div>

    </div> <!-- /container -->
<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>